# Generated by Django 5.2 on 2025-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_conversaciondirecta_solicitudsoporte_admin_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='zona_asignada',
            field=models.CharField(blank=True, choices=[('zona_1_sur', 'Zona 1 - Sur'), ('zona_2_centro', 'Zona 2 - Centro'), ('zona_3_norte', 'Zona 3 - Norte')], help_text='Zona asignada para conductores', max_length=20, null=True),
        ),
    ]
