# Generated by Django 5.2.1 on 2025-12-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_usuario_zona_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona_asignada',
            field=models.CharField(blank=True, choices=[('zona_1_sur', 'Zona 1 - Sur (Comunas 9, 13)'), ('zona_2_centro', 'Zona 2 - Centro (Comunas 1, 3, 10, 12)'), ('zona_3_norte', 'Zona 3 - Norte (Comunas 2, 5, 6, 7, 8)')], help_text='Zona asignada para conductores', max_length=20, null=True),
        ),
    ]
