# Generated by Django 5.2.1 on 2025-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_motivo_to_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='motivo_reagendamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
