# Generated by Django 5.2.1 on 2025-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_motivo_reagendamiento_to_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('canje_pendiente', 'Canje Pendiente'), ('canje_aprobado', 'Canje Aprobado'), ('canje_rechazado', 'Canje Rechazado'), ('redencion_pendiente', 'Redención Pendiente'), ('redencion_aprobada', 'Redención Aprobada'), ('redencion_rechazada', 'Redención Rechazada'), ('recompensa_canjeada', 'Recompensa Canjeada'), ('retiro_enviado', 'Retiro Enviado'), ('ruta_confirmada', 'Ruta Confirmada'), ('ruta_rechazada', 'Ruta Rechazada'), ('ruta_reagendada', 'Ruta Reagendada'), ('seguimiento_actualizado', 'Seguimiento Actualizado'), ('perfil_actualizado', 'Perfil Actualizado'), ('password_cambiado', 'Contraseña Cambiada'), ('foto_actualizada', 'Foto Actualizada'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
    ]
